name: Mountain Tea
favicon: null
layout_spectrum: 0.7515
typography_spectrum: 0.68783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dce7e9'
    - '#bfb6ad'
    - '#746055'
    - '#8a341f'
  brandStrength: 0.5
  lightness: 0.4638382575940341
  saturation: 0.15465914062224329
  rhythmicContrast: 0.4279380396474153
purpose: []
